---
- name: create database
  become_user: postgres
  postgresql_db:
    name: "{{ POSTGRES_DB }}"

- name: create database user
  become_user: postgres
  postgresql_user:
    db: "{{ POSTGRES_DB }}"
    name: "{{ POSTGRES_USER }}"
    password: "{{ POSTGRES_PASSWORD }}"