# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-25 23:59
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.IntegerField()),
                ('priority', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('anchor', models.CharField(max_length=1000, verbose_name='Anchor')),
                ('requirements', models.CharField(max_length=1000, verbose_name='Requirements')),
                ('user_agent', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='User Agent')),
                ('category', models.CharField(blank=True, choices=[('Android', 'Android'), ('Downloads', 'Downloads'), ('Email Submits', 'Email Submits'), ('Free', 'Free'), ('Gifts', 'Gifts'), ('Hard Incentives', 'Hard Incentives'), ('Health & Beauty', 'Health & Beauty'), ('Home & Garden', 'Home & Garden'), ('iOS Devices', 'iOS Devices'), ('iPad', 'iPad'), ('iPhone', 'iPhone'), ('Lead Gen', 'Lead Gen'), ('Mobile Subscription', 'Mobile Subscription'), ('Mobile WAP', 'Mobile WAP'), ('Online Services', 'Online Services'), ('PIN Submit', 'PIN Submit'), ('Samsung devices', 'Samsung devices'), ('Special Requests', 'Special Requests'), ('Surveys', 'Surveys'), ('', '')], max_length=50, null=True, verbose_name='Category')),
                ('earnings_per_click', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='EPC')),
                ('country', models.CharField(max_length=747)),
                ('flag', models.CharField(max_length=5, verbose_name='Country')),
                ('country_count', models.IntegerField()),
                ('payout', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Payout')),
                ('success_rate', models.FloatField(verbose_name='Success Rate')),
                ('tracking_url', models.CharField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('clicks', models.IntegerField(default=0, verbose_name='Clicks')),
                ('leads', models.IntegerField(default=0)),
                ('clicks_today', models.IntegerField(default=0, verbose_name="Today's Clicks")),
                ('leads_today', models.IntegerField(default=0, verbose_name="Today's Leads")),
                ('today', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Today')),
                ('yesterday', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Yesterday')),
                ('week', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Week')),
                ('month', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Month')),
                ('yestermonth', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Last Month')),
                ('year', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Year')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Total')),
                ('real_today', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='*Today')),
                ('real_month', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='*Month')),
                ('real_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='*Total')),
                ('obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='offers.Offer')),
            ],
            options={
                'verbose_name_plural': 'Earnings',
            },
        ),
    ]
