CATEGORY_TYPES = (
	("Android", "Android"),
	("Downloads", "Downloads"),
	("Email Submits", "Email Submits"),
	("Free", "Free"),
	("Gifts", "Gifts"),
	("Hard Incentives", "Hard Incentives"),
	("Health & Beauty", "Health & Beauty"),
	("Home & Garden", "Home & Garden"),
	("iOS Devices", "iOS Devices"),
	("iPad", "iPad"),
	("iPhone", "iPhone"),
	("Conversion Gen", "Conversion Gen"),
	("Mobile Subscription", "Mobile Subscription"),
	("Mobile WAP", "Mobile WAP"),
	("Online Services", "Online Services"),
	("PIN Submit", "PIN Submit"),
	("Samsung devices", "Samsung devices"),
	("Special Requests", "Special Requests"),
	("Surveys", "Surveys"),
	("", "")
)


CATEGORY_TYPES_ICONS = {
	"Android" 				: "android",
	"Downloads"				: "download",
	"Email Submits"			: "mail outline",
	"Free"					: "certificate",
	"Gifts"					: "gift",
	"Hard Incentives"		: "bomb",
	"Health & Beauty"		: "female",
	"Home & Garden"			: "home",
	"iOS Devices"			: "apple",
	"iPad"					: "tablet",
	"iPhone"				: "mobile",
	"Conversion Gen"		: "lightning",
	"Mobile Subscription"	: "mobile",
	"Mobile WAP"			: "mobile",
	"Mobile Content"		: "mobile",
	"Online Services"		: "desktop",
	"PIN Submit"			: "mobile",
	"Samsung devices"		: "mobile",
	"Special Requests"		: "checkered flag",
	"Surveys"				: "checkmark",
}