#!/bin/bash
cd $(dirname $0)
find ../ -name "*.pyc" -type f -delete

echo "Cleaned python files"

if [ "$1" = "migrations" ]; then
	cd ../project/
	find . -path "*/migrations/*.py" -not -name "__init__.py" -delete
	echo "Cleaned migration files"
fi
