#!/bin/bash
cd ../project/viking/
echo "Updating GeoLite2 City Database"
wget http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz
gunzip GeoLite2-City.mmdb.gz
rm GeoLite2-City.mmdb.gz