#!/bin/bash

# apt-get install npm
# npm install -g less less-plugin-clean-css

cd $(dirname $0)/../
cd static/css/_less/
echo
echo ... Compiling
#lessc --compress semantic.less > ../semantic.min.css
lessc semantic.less --clean-css="--s1 --advanced --compatibility=ie8" > ../semantic.min.css
echo ... Done
