#!/bin/bash

cd "${0%/*}"
cd ../
source env/bin/activate
cd project/

case "$1" in
	start)
		gunicorn --workers=4 siren.wsgi &
		celery worker --app=siren --beat --loglevel=INFO &
		;;
	stop)
		pkill gunicorn &
		pkill celery & 
		;;
	*)
		echo "Usage: rungunicorn {start|stop}"
		exit 1
		;;
esac

exit 0