#!/bin/bash

cd $(dirname $0)/../
source env/bin/activate
cd project/

case "$1" in
	start)
		gunicorn --workers=4 viking.wsgi &
		celery worker --app=viking --beat --events --loglevel=INFO &
		../scripts/manage celerycam --frequency=30.0 &
		;;
	stop)
		pkill gunicorn &
		pkill celery & 
		pkill python & 
		pkill python3 &
		kill `ps ax| grep -v awk| awk '/celerycam/{print $1}'`
		;;
	restart)
		./runproduction stop
		./runproduction start
		;;
	*)
		echo "Usage: rungunicorn {start|stop|restart}"
		exit 1
		;;
esac

exit 0