# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 11:05
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0008_party'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('clicks', models.IntegerField(default=0, verbose_name='Clicks')),
                ('leads', models.IntegerField(default=0)),
                ('clicks_today', models.IntegerField(default=0, verbose_name="Today's Clicks")),
                ('leads_today', models.IntegerField(default=0, verbose_name="Today's Leads")),
                ('today', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Today')),
                ('yesterday', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Yesterday')),
                ('week', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Week')),
                ('month', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Month')),
                ('yestermonth', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Last Month')),
                ('year', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Year')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Total')),
                ('real_today', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='*Today')),
                ('real_month', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='*Month')),
                ('real_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='*Total')),
                ('obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('wallet', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
            ],
            options={
                'verbose_name_plural': 'Earnings',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('notification_lead', models.IntegerField(default=0)),
                ('notification_billing', models.IntegerField(default=0)),
                ('offer_block', models.ManyToManyField(blank=True, related_name='offer_block', to='offers.Offer')),
                ('offer_priority', models.ManyToManyField(blank=True, related_name='offer_priority', to='offers.Offer')),
                ('party', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Party')),
            ],
        ),
        migrations.CreateModel(
            name='Referral_Earnings',
            fields=[
                ('clicks', models.IntegerField(default=0, verbose_name='Clicks')),
                ('leads', models.IntegerField(default=0)),
                ('clicks_today', models.IntegerField(default=0, verbose_name="Today's Clicks")),
                ('leads_today', models.IntegerField(default=0, verbose_name="Today's Leads")),
                ('today', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Today')),
                ('yesterday', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Yesterday')),
                ('week', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Week')),
                ('month', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Month')),
                ('yestermonth', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Last Month')),
                ('year', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Year')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Total')),
                ('real_today', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='*Today')),
                ('real_month', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='*Month')),
                ('real_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='*Total')),
                ('obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Referral Earnings',
                'verbose_name': 'Referral Earnings',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='referrer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrer_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
